url_base = 'https://www.instagram.com/'
url_tag = 'https://www.instagram.com/explore/tags/{}/?__a=1'
url_likes = 'https://www.instagram.com/web/likes/{}/like/'
url_unlike = 'https://www.instagram.com/web/likes/{}/unlike/'
url_comment = 'https://www.instagram.com/web/comments/{}/add/'
url_follow = 'https://www.instagram.com/web/friendships/{}/follow/'
url_unfollow = 'https://www.instagram.com/web/friendships/{}/unfollow/'
url_login = 'https://www.instagram.com/accounts/login/ajax/'
url_logout = 'https://www.instagram.com/accounts/logout/'
url_media_detail = 'https://www.instagram.com/p/{}/?__a=1'
url_user = 'https://www.instagram.com/{}/?__a=1'

url_external_ip = 'https://api.ipify.org?format=json'
